
set(RAPIDJSON_CMAKE_ARGS "-DRAPIDJSON_BUILD_DOC=OFF")
set(RAPIDJSON_CMAKE_ARGS "${RAPIDJSON_CMAKE_ARGS};-DRAPIDJSON_BUILD_EXAMPLES=OFF")
set(RAPIDJSON_CMAKE_ARGS "${RAPIDJSON_CMAKE_ARGS};-DRAPIDJSON_BUILD_TESTS=OFF")
set(RAPIDJSON_CMAKE_ARGS "${RAPIDJSON_CMAKE_ARGS};-DRAPIDJSON_BUILD_THIRDPARTY_GTEST=OFF")
set(RAPIDJSON_CMAKE_ARGS "${RAPIDJSON_CMAKE_ARGS};-DRAPIDJSON_BUILD_CXX11=ON")
set(RAPIDJSON_CMAKE_ARGS "${RAPIDJSON_CMAKE_ARGS};-DRAPIDJSON_HAS_STDSTRING=ON")

add_git_package(${DEPENDENCY_PACKAGE_NAME} "https://github.com/miloyip/rapidjson" GIT_TAG ${ADD_PACKAGE_VERSION} CMAKE_ARGS ${RAPIDJSON_CMAKE_ARGS})

#set_target_properties(RapidJSON PROPERTIES FOLDER "packages")

set(${DEPENDENCY_PACKAGE_NAME}_INCLUDE_DIRS "${DEPENDENCY_PACKAGE_INSTALL_DIR}/include" PARENT_SCOPE)
#set(${DEPENDENCY}_LIBRARIES "${DEPENDENCY_PACKAGE_DIR}/lib/${DEPENDENCY}.lib" PARENT_SCOPE)
