add_git_package(${DEPENDENCY_PACKAGE_NAME} "https://github.com/g-truc/glm.git" GIT_TAG ${ADD_PACKAGE_VERSION})

set(${DEPENDENCY_PACKAGE_NAME}_INCLUDE_DIRS "${DEPENDENCY_PACKAGE_INSTALL_DIR}/include" PARENT_SCOPE)
